export const SET_DELIVEROO_REQUEST = "SET_DELIVEROO_REQUEST";
export const SET_DELIVEROO_SUCCESS = "SET_DELIVEROO_SUCCESS";
export const SET_DELIVEROO_ERROR = "SET_DELIVEROO_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const SHIPPING_COST = 2.5;
